import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import TopLeftImg from "@/components/TopLeftImg";
import Header from "@/components/Header";
import { TransitionProvider } from "@/components/TransitionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TransitionProvider />
          <TopLeftImg />
          <Nav />
          <Header />
          {children}
     
      </body>
    </html>
  );
}
